# Deep Learning via ANN

### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

### Importing Dataset

In [3]:
dataset = pd.read_csv("american_exp.csv")

In [4]:
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


### Enconding Categorical data

### Gender Column : Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [7]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


### Geography Column : One Hot Encoding

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [1])], remainder = "passthrough")
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


### Splitting dataset into training and test dataset

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 21)

### Feature Scaling of the model

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## ANN

### Initialization

In [12]:
from keras.models import Sequential
from keras.layers import Dense

In [13]:
ann = Sequential()

### Adding Inpu Layer and First Hidden Layer

In [14]:
ann.add(Dense(64, input_shape = (11, ), activation = "relu"))

### Adding Second Hidden Layer

In [15]:
ann.add(Dense(32, activation = "relu"))

### Adding Output Layer

In [16]:
ann.add(Dense(1, activation = "sigmoid"))

## ANN Training 

### Compiling

In [17]:
ann.compile(optimizer = "adam", 
            loss = "binary_crossentropy", 
            metrics = ["accuracy"])

### Training on dataset

In [18]:
ann.fit(X_train, y_train, epochs = 120, batch_size =32)

Epoch 1/120
249/249 [==============================] - 1s 581us/step - loss: 0.4689 - accuracy: 0.7956
Epoch 2/120
249/249 [==============================] - 0s 581us/step - loss: 0.4153 - accuracy: 0.8160
Epoch 3/120
249/249 [==============================] - 0s 577us/step - loss: 0.3889 - accuracy: 0.8333
Epoch 4/120
249/249 [==============================] - 0s 577us/step - loss: 0.3722 - accuracy: 0.8432
Epoch 5/120
249/249 [==============================] - 0s 569us/step - loss: 0.3624 - accuracy: 0.8452
Epoch 6/120
249/249 [==============================] - 0s 569us/step - loss: 0.3556 - accuracy: 0.8513
Epoch 7/120
249/249 [==============================] - 0s 577us/step - loss: 0.3526 - accuracy: 0.8496
Epoch 8/120
249/249 [==============================] - 0s 569us/step - loss: 0.3499 - accuracy: 0.8528
Epoch 9/120
249/249 [==============================] - 0s 573us/step - loss: 0.3471 - accuracy: 0.8525
Epoch 10/120
249/249 [==============================] - 0s 577us/step - l

### Predictions

### Single Prediction

In [19]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 [==============================] - 0s 52ms/step
[[False]]


### Prediction on dataset

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 468us/step
[[0 0]
 [0 0]
 [0 1]
 ...
 [0 1]
 [0 0]
 [0 0]]


### Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1493  109]
 [ 205  179]]


0.8418932527693856

## So therefore we get a Artificical Neural Network with an accuracy of 84.18 % (approx.)